### ISSUE TITLE
Oncotator : IndexError exception in the middle of the script

### ISSUE THREAD

**Issue by vigneshravi** [broadinstitute/oncotator#321]
I ran oncotator on a HC called VCF using the command

oncotator -i VCF -o VCF --db-dir /path_to/ngstools/oncotator_v1_ds_Jan262014/ Project_bwa_GatkHC.vcf Project_bwa_GatkHC_oncotator.vcf hg19

The script ran for about 214000 mutations and threw an exception. Pasting the error below. Can someone help me understand this error?

2015-06-11 13:11:58,655 INFO [oncotator.output.OutputDataManager:194] Wrote 214000 mutations to tsv.

Traceback (most recent call last):
  File "/home/Pythonmodules/bin/oncotator", line 9, in <module>
    load_entry_point('Oncotator==v1.5.1.0', 'console_scripts', 'oncotator')()
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Oncotator.py", line 292, in main
    annotator.annotate()
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py", line 403, in annotate
    filename = self._outputRenderer.renderMutations(mutations, metadata=metadata, comments=comments)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/output/VcfOutputRenderer.py", line 118, in renderMutations
    dataManager = OutputDataManager(self.configTable, mutations, comments, metadata, path)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/output/OutputDataManager.py", line 92, in __init__
    self.chroms, self.sampleNames, self.filename = self._writeMuts2Tsv(self.mutations, path)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/output/OutputDataManager.py", line 160, in _writeMuts2Tsv
    for mut in muts:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py", line 414, in _applyManualAnnotations
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py", line 422, in _applyDefaultAnnotations
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py", line 470, in _annotate_mutations_using_datasources
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/input/VcfInputMutationCreator.py", line 306, in createMutations
    sampleMut = self._addGenotypeData2Mutation(sampleMut, record, index)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/input/VcfInputMutationCreator.py", line 130, in _addGenotypeData2Mutation
    val = genotypeData[ID][index]
IndexError: list index out of range

**Comment by LeeTL1220** [comment]
Try updating the version.

On Thu, Jun 11, 2015 at 1:56 PM, Vignesh Ravichandran <
notifications@github.com> wrote:

> I ran oncotator on a HC called VCF using the command
>
> oncotator -i VCF -o VCF --db-dir
> /path_to/ngstools/oncotator_v1_ds_Jan262014/ Project_bwa_GatkHC.vcf
> Project_bwa_GatkHC_oncotator.vcf hg19
>
> The script ran for about 214000 mutations and threw an exception. Pasting
> the error below. Can someone help me understand this error?
>
> 2015-06-11 13:11:58,655 INFO [oncotator.output.OutputDataManager:194]
> Wrote 214000 mutations to tsv.
>
> Traceback (most recent call last):
> File "/home/Pythonmodules/bin/oncotator", line 9, in
> load_entry_point('Oncotator==v1.5.1.0', 'console_scripts', 'oncotator')()
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Oncotator.py",
> line 292, in main
> annotator.annotate()
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py",
> line 403, in annotate
> filename = self.
>
>
> *outputRenderer.renderMutations(mutations, metadata=metadata,
> comments=comments) File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/output/VcfOutputRenderer.py",
> line 118, in renderMutations dataManager =
> OutputDataManager(self.configTable, mutations, comments, metadata, path)
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/output/OutputDataManager.py",
> line 92, in __init_*
> self.chroms, self.sampleNames, self.filename =
> self._writeMuts2Tsv(self.mutations, path)
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/output/OutputDataManager.py",
> line 160, in _writeMuts2Tsv
> for mut in muts:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py",
> line 414, in _applyManualAnnotations
> for m in mutations:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py",
> line 422, in _applyDefaultAnnotations
> for m in mutations:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/Annotator.py",
> line 470, in _annotate_mutations_using_datasources
> for m in mutations:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/input/VcfInputMutationCreator.py",
> line 306, in createMutations
> sampleMut = self._addGenotypeData2Mutation(sampleMut, record, index)
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.5.1.0-py2.7.egg/oncotator/input/VcfInputMutationCreator.py",
> line 130, in _addGenotypeData2Mutation
> val = genotypeData[ID][index]
> IndexError: list index out of range
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/oncotator/issues/321>.
>



-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632

**Comment by vigneshravi** [comment]
I did! I still get the same error.

**Comment by LeeTL1220** [comment]
Version 1.5.2.0 or greater has a fix

**Comment by vigneshravi** [comment]
I updated oncotator to v1.8.0 and tried it which still gave the error

**Comment by LeeTL1220** [comment]
Send me the stack trace, if you can.


On Fri, Jun 19, 2015 at 12:51 PM, Vignesh Ravichandran <
notifications@github.com> wrote:

> I updated oncotator to v1.8.0 and tried it which still gave the error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/oncotator/issues/321#issuecomment-113572561>
> .
>



-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632

**Comment by vigneshravi** [comment]
Traceback (most recent call last):
  File "/home/Pythonmodules/bin/oncotator", line 9, in <module>
    load_entry_point('Oncotator==v1.8.0.0dev', 'console_scripts', 'oncotator')()
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Oncotator.py", line 293, in main
    annotator.annotate()
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py", line 433, in annotate
    filename = self._outputRenderer.renderMutations(mutations, metadata=metadata, comments=comments)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/output/VcfOutputRenderer.py", line 118, in renderMutations
    dataManager = OutputDataManager(self.configTable, mutations, comments, metadata, path)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/output/OutputDataManager.py", line 92, in __init__
    self.chroms, self.sampleNames, self.filename = self._writeMuts2Tsv(self.mutations, path)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/output/OutputDataManager.py", line 160, in _writeMuts2Tsv
    for mut in muts:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py", line 444, in _applyManualAnnotations
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py", line 452, in _applyDefaultAnnotations
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py", line 500, in _annotate_mutations_using_datasources
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/input/VcfInputMutationCreator.py", line 316, in createMutations
    sampleMut = self._addFormatData2Mutation(sampleMut, record, index)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/input/VcfInputMutationCreator.py", line 141, in _addFormatData2Mutation
    val = genotypeData[ID][index]
IndexError: list index out of range

**Comment by LeeTL1220** [comment]
Are you running off the develop branch?  Oncotator 1.8.0.0 does not exist
yet.  1.7.1.0 is the latest.

On Fri, Jun 19, 2015 at 12:54 PM, Vignesh Ravichandran <
notifications@github.com> wrote:

> Traceback (most recent call last):
> File "/home/Pythonmodules/bin/oncotator", line 9, in
> load_entry_point('Oncotator==v1.8.0.0dev', 'console_scripts',
> 'oncotator')()
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Oncotator.py",
> line 293, in main
> annotator.annotate()
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py",
> line 433, in annotate
> filename = self.
>
>
> *outputRenderer.renderMutations(mutations, metadata=metadata,
> comments=comments) File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/output/VcfOutputRenderer.py",
> line 118, in renderMutations dataManager =
> OutputDataManager(self.configTable, mutations, comments, metadata, path)
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/output/OutputDataManager.py",
> line 92, in __init_*
> self.chroms, self.sampleNames, self.filename =
> self._writeMuts2Tsv(self.mutations, path)
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/output/OutputDataManager.py",
> line 160, in _writeMuts2Tsv
> for mut in muts:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py",
> line 444, in _applyManualAnnotations
> for m in mutations:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py",
> line 452, in _applyDefaultAnnotations
> for m in mutations:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/Annotator.py",
> line 500, in _annotate_mutations_using_datasources
> for m in mutations:
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/input/VcfInputMutationCreator.py",
> line 316, in createMutations
> sampleMut = self._addFormatData2Mutation(sampleMut, record, index)
> File
> "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.8.0.0dev-py2.7.egg/oncotator/input/VcfInputMutationCreator.py",
> line 141, in _addFormatData2Mutation
> val = genotypeData[ID][index]
> IndexError: list index out of range
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/oncotator/issues/321#issuecomment-113573832>
> .
>



-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632

**Comment by vigneshravi** [comment]
I just dowmloaded from git. Could you point me to the 1.7.1 downloadable link please?

**Comment by vigneshravi** [comment]
I think I found it!

**Comment by LeeTL1220** [comment]
If you just cone from git, you get develop, which is standard for a git repo

**Comment by LeeTL1220** [comment]
Any luck?

On Fri, Jun 19, 2015 at 1:01 PM, Lee Lichtenstein <
lichtens@broadinstitute.org> wrote:

> If you just cone from git, you get develop, which is standard for a git
> repo
> On Jun 19, 2015 12:59 PM, "Vignesh Ravichandran" <notifications@github.com>
> wrote:
>
>> I think I found it!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/broadinstitute/oncotator/issues/321#issuecomment-113575998>
>> .
>>
>


-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632

**Comment by vigneshravi** [comment]
I still am getting the same error 
Traceback (most recent call last):
  File "/home/Pythonmodules/bin/oncotator", line 9, in <module>
    load_entry_point('Oncotator==v1.7.1.0', 'console_scripts', 'oncotator')()
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/Oncotator.py", line 293, in main
    annotator.annotate()
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/Annotator.py", line 433, in annotate
    filename = self._outputRenderer.renderMutations(mutations, metadata=metadata, comments=comments)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/output/VcfOutputRenderer.py", line 118, in renderMutations
    dataManager = OutputDataManager(self.configTable, mutations, comments, metadata, path)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/output/OutputDataManager.py", line 92, in __init__
    self.chroms, self.sampleNames, self.filename = self._writeMuts2Tsv(self.mutations, path)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/output/OutputDataManager.py", line 160, in _writeMuts2Tsv
    for mut in muts:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/Annotator.py", line 444, in _applyManualAnnotations
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/Annotator.py", line 452, in _applyDefaultAnnotations
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/Annotator.py", line 500, in _annotate_mutations_using_datasources
    for m in mutations:
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/input/VcfInputMutationCreator.py", line 316, in createMutations
    sampleMut = self._addFormatData2Mutation(sampleMut, record, index)
  File "/home/Pythonmodules/lib/python2.7/site-packages/Oncotator-v1.7.1.0-py2.7.egg/oncotator/input/VcfInputMutationCreator.py", line 141, in _addFormatData2Mutation
    val = genotypeData[ID][index]
IndexError: list index out of range

**Comment by LeeTL1220** [comment]
Can you give me the input file?  Or the part that causes the crash?

**Comment by vigneshravi** [comment]
I am unable to attache the vcf. Can I get your email id to send and receive the comments. I was able to identify the line that causes this err but couldnt figure out why

**Comment by LeeTL1220** [comment]
Send it to oncotator@broadinstitute.org

On Mon, Jun 22, 2015 at 1:06 PM, Vignesh Ravichandran <
notifications@github.com> wrote:

> I am unable to attache the vcf. Can I get your email id to send and
> receive the comments. I was able to identify the line that causes this err
> but couldnt figure out why
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/oncotator/issues/321#issuecomment-114180365>
> .
>



-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632

**Comment by LeeTL1220** [comment]
This seems to have been induced by poorly formed input file.  Will re-open if this is not the case.
