### ISSUE TITLE
Cache filename too long?

### ISSUE THREAD

**Issue by lebolo** [broadinstitute/oncotator#355]
I'm using oncotator v1.9.0.0 and am trying to create a file cache to speed up VCF to MAF. I get the error pasted below.  I **think** the problem is that Linux has a filename length limit of 255 and the filename for this mutation is 299. The VCF has ~7M mutations, so the cache is quite large but I'll try to see if there are any other filenames greater than 255.

Any thoughts on how I can fix this without modifying oncotator code?

```
2016-09-09 10:12:28,501 ERROR [oncotator.output.TcgaMafOutputRenderer:333] Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/oncotator/output/TcgaMafOutputRenderer.py", line 321, in renderMutations
    for m in mutations:
  File "build/bdist.linux-x86_64/egg/oncotator/Annotator.py", line 448, in _applyManualAnnotations
    for m in mutations:
  File "build/bdist.linux-x86_64/egg/oncotator/Annotator.py", line 456, in _applyDefaultAnnotations
    for m in mutations:
  File "build/bdist.linux-x86_64/egg/oncotator/Annotator.py", line 523, in _annotate_mutations_using_datasources
    self._cacheManager.store_annotations_in_cache(m)
  File "build/bdist.linux-x86_64/egg/oncotator/cache/CacheManager.py", line 85, in store_annotations_in_cache
    self._store_basic_annotations_in_cache(cache_key, annotations)
  File "build/bdist.linux-x86_64/egg/oncotator/cache/CacheManager.py", line 91, in _store_basic_annotations_in_cache
    self.get_cache().store_into_cache(key, annotations)
  File "build/bdist.linux-x86_64/egg/oncotator/cache/ShoveCache.py", line 71, in store_into_cache
    self.db[key] = value
  File "/opt/conda/lib/python2.7/site-packages/shove-0.6.6-py2.7.egg/shove/core.py", line 44, in __setitem__
    self.sync()
  File "/opt/conda/lib/python2.7/site-packages/shove-0.6.6-py2.7.egg/shove/core.py", line 74, in sync
    self._store.update(self._buffer)
  File "/opt/conda/lib/python2.7/_abcoll.py", line 566, in update
    self[key] = other[key]
  File "/opt/conda/lib/python2.7/site-packages/shove-0.6.6-py2.7.egg/shove/base.py", line 123, in __setitem__
    raise KeyError(key)
KeyError: '12_62775059_62775301_ATTTATTATAAGTAATTATTTTGAAATTTGGGAAATGAATAGTTGAGTACATCATTTGAGTGTTTATTTGACCAGTTATTAGTGCAAGAAACCATCATTTAAATGTTCTCTGTGTTATAGCAAATCAATTTGTTTCTCTCTTCATATTAATGTGTTTTAAGAAAAATTCATTATGATTACTTTTACTTGAAAATATATTTTATTTTTTGCAGTGTTTGAGCAACACACCTCCACTTACTGAGT_-_16348fb8e83ab2e686dfc2a90986f498'

2016-09-09 10:12:28,501 ERROR [oncotator.output.TcgaMafOutputRenderer:334] Error at mutation 1746159 ['12', 62775059, 62775301, 'ATTTATTATAAGTAATTATTTTGAAATTTGGGAAATGAA  TAGTTGAGTACATCATTTGAGTGTTTATTTGACCAGTTATTAGTGCAAGAAACCATCATTTAAATGTTCTCTGTGTTATAGCAAATCAATTTGTTTCTCTCTTCATATTAATGTGTTTTAAGAAAAATTCATTATGATTACTTTTACTTGAAAATATATTTTATTTTT  TGCAGTGTTTGAGCAACACACCTCCACTTACTGAGT', '-']:
2016-09-09 10:12:28,501 ERROR [oncotator.output.TcgaMafOutputRenderer:335] Incomplete: rendered 1746159 mutations.
Traceback (most recent call last):
  File "/opt/conda/bin/oncotator", line 11, in <module>
    load_entry_point('Oncotator==1.9.0.0', 'console_scripts', 'oncotator')()
  File "build/bdist.linux-x86_64/egg/oncotator/Oncotator.py", line 309, in main
  File "build/bdist.linux-x86_64/egg/oncotator/Annotator.py", line 437, in annotate
  File "build/bdist.linux-x86_64/egg/oncotator/output/TcgaMafOutputRenderer.py", line 337, in renderMutations
KeyError: '12_62775059_62775301_ATTTATTATAAGTAATTATTTTGAAATTTGGGAAATGAATAGTTGAGTACATCATTTGAGTGTTTATTTGACCAGTTATTAGTGCAAGAAACCATCATTTAAATGTTCTCTGTGTTATAGCAAATCAATTTGTTTC  TCTCTTCATATTAATGTGTTTTAAGAAAAATTCATTATGATTACTTTTACTTGAAAATATATTTTATTTTTTGCAGTGTTTGAGCAACACACCTCCACTTACTGAGT_-_16348fb8e83ab2e686dfc2a90986f498'
```

**Comment by LeeTL1220** [comment]
What is ``trimmed.cache``?  Is that a proper datasource dir?

Also, are you sure that your VCF is valid at this mutation?  It looks like it has spaces in it...

**Comment by lebolo** [comment]
`trimmed.cache` is a proper datasource directory. If I remove the caching option, Oncotator successfully runs through the whole VCF using this configuration. The spaces are an artifact of my copy-pasting, it's a valid VCF throughout.
