### ISSUE TITLE
Is really only enum34-1.1.2 supported

### ISSUE THREAD

**Issue by mmokrejs** [broadinstitute/oncotator#365]
$ Oncotator 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/Oncotator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34==1.1.2' distribution was not found and is required by Oncotator
$

I have 1.1.6 version installed. Is it incompatible?

I saw a lot more dependencies in setup.py with '==' sign instead of '>=". Do you intentionally require just those versions? Please inlcude anyway the required version in README.md in a proper section.

**Comment by lbergelson** [comment]
@mmokrejs I would expect 1.1.6 to be compatible, but it's untested so we don't make any guarantee.  If they're following proper semantic versioning it should be fine, but many packages in the past have made incompatible updates in minor and bugfix versions so we peg to specific known working versions.
