### ISSUE TITLE
Potentially something wrong with the current DB pack?

### ISSUE THREAD

**Issue by JohnMCMa** [broadinstitute/oncotator#375]
I just installed Oncotator v1.9.9.0 on Python 2.7.15, and using it with the current annotation DB (`oncotator_v1_ds_April052016`). I got an error associated with the COSMIC annotation; what could be happening here?
```
oncotator -v --no-multicore -i VCF --db-dir ~/oncotator_v1_ds_April052016 -o TCGAMAF "/rsrch3/scratch/lym_myl_rsch/mma/Green/WGS/Biovest/output/PM1008/FLC03/FLC03.SNV.final.vcf" "/rsrch3/scratch/lym_myl_rsch/mma/Green/WGS/Biovest/output/PM1008/FLC03/FLC03.SNV.final.maf" hg19
Verbose mode on
Path:
['/rsrch3/home/lym_myl_rsch/mma/.local/bin', '/risapps/rhel7/python/2.7.15/lib/python27.zip', '/risapps/rhel7/python/2.7.15/lib/python2.7', '/risapps/rhel7/python/2.7.15/lib/python2.7/plat-linux2', '/risapps/rhel7/python/2.7.15/lib/python2.7/lib-tk', '/risapps/rhel7/python/2.7.15/lib/python2.7/lib-old', '/risapps/rhel7/python/2.7.15/lib/python2.7/lib-dynload', '/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages', '/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/misopy-0.5.4-py2.7-linux-x86_64.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/colorbrewer-0.2.0-py2.7.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/gdc_client-1.3.0-py2.7.egg', '/risapps/build7/CellProfiler-Analyst', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/sequenza_utils-3.0.0-py2.7-linux-x86_64.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/trust-3.0.3-py2.7-linux-x86_64.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/regex-2019.6.8-py2.7-linux-x86_64.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/parasail-1.1.17-py2.7.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/multiprocessing-2.6.2.1-py2.7-linux-x86_64.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/genomedata-1.3.6-py2.7.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/hgtools-8.1.1-py2.7.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/optbuild-0.2.1-py2.7.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/optplus-0.2-py2.7.egg', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages', '/risapps/rhel7/python/2.7.15/lib/python2.7/site-packages/textinput-0.2.0-py2.7.egg']

2019-07-17 11:22:36,725 INFO [oncotator.Oncotator:241] Oncotator v1.9.9.0
2019-07-17 11:22:36,726 INFO [oncotator.Oncotator:242] Args: Namespace(allow_overwriting=False, cache_url=None, canonical_tx_file=None, collapse_filter_cols=False, collapse_number_annotations=False, dbDir='/rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016', default_cli=[], default_config=None, genome_build='hg19', infer_genotypes='false', infer_onps=False, input_file='/rsrch3/scratch/lym_myl_rsch/mma/Green/WGS/Biovest/output/PM1008/FLC03/FLC03.SNV.final.vcf', input_format='VCF', log_name='oncotator.log', longer_other_tx=False, noMulticore=True, output_file='/rsrch3/scratch/lym_myl_rsch/mma/Green/WGS/Biovest/output/PM1008/FLC03/FLC03.SNV.final.maf', output_format='TCGAMAF', override_cli=[], override_config=None, prepend=False, prune_filter_cols=False, read_only_cache=False, reannotate_tcga_maf_cols=False, skip_no_alt=False, tx_mode='CANONICAL', verbose=6)
2019-07-17 11:22:36,726 INFO [oncotator.Oncotator:243] Log file: /rsrch3/scratch/lym_myl_rsch/mma/Green/ATAC-seq/BCL7/fastq/QD-ATAC_PM1044/oncotator.log
2019-07-17 11:22:36,726 WARNING [oncotator.Oncotator:249] ngslib module not installed.  Will be unable to annotate with BigWig datasources.
2019-07-17 11:22:36,744 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/ccle_by_gp/hg19/ccle_by_gp.config
2019-07-17 11:22:36,745 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/uniprot_aa_xform/hg19/uniprot_aa_xform.config
2019-07-17 11:22:36,746 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/exac/hg19/exac.config
2019-07-17 11:22:36,746 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/gencode_xrefseq/hg19/gencode_xrefseq.config
2019-07-17 11:22:36,747 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/simple_uniprot/hg19/simple_uniprot.config
2019-07-17 11:22:36,748 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/ccle_by_gene/hg19/ccle_by_gene.config
2019-07-17 11:22:36,749 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/gencode_out2/hg19/gencode_out2.config
2019-07-17 11:22:36,749 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/cosmic/hg19/cosmic.config
2019-07-17 11:22:36,750 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/cosmic_fusion/hg19/cosmic_fusion.config
2019-07-17 11:22:36,750 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/clinvar/hg19/clinvar.config
2019-07-17 11:22:36,750 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/cancer_gene_census/hg19/cancer_gene_census.config
2019-07-17 11:22:36,752 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/ref_hg/hg19/ref_hg.config
2019-07-17 11:22:36,752 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/familial/hg19/familial.config
2019-07-17 11:22:36,753 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/cosmic_tissue/hg19/cosmic_tissue.config
2019-07-17 11:22:36,754 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/oreganno/hg19/oreganno.config
2019-07-17 11:22:36,755 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/tumorscape/hg19/tumorscape.config
2019-07-17 11:22:36,755 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/dbNSFP_ds/hg19/dbNSFP_ds.config
2019-07-17 11:22:36,756 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/achilles/hg19/achilles.config
2019-07-17 11:22:36,757 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/hgnc/hg19/hgnc.config
2019-07-17 11:22:36,757 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/dna_repair_genes/hg19/dna_repair_genes.config
2019-07-17 11:22:36,758 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/uniprot_aa_annotation/hg19/uniprot_aa_annotation.config
2019-07-17 11:22:36,758 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/tcgascape/hg19/tcgascape.config
2019-07-17 11:22:36,759 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/mutsig/hg19/mutsig.config
2019-07-17 11:22:36,760 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/1000genome_db/hg19/1000genome_db.config
2019-07-17 11:22:36,761 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/dbsnp/hg19/dbsnp.config
2019-07-17 11:22:36,762 INFO [oncotator.DatasourceFactory:286] Queuing datasource creation for /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/so_terms/hg19/so_terms.config
2019-07-17 11:22:36,768 INFO [root:73] Loading /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/ccle_by_gp/hg19//ccle_results_by_pos.hg19.import.bin...
2019-07-17 11:22:37,014 INFO [root:73] Loading /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/gencode_xrefseq/hg19//gencode_xrefseq_v19.bin...
2019-07-17 11:22:37,264 INFO [root:73] Loading /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/simple_uniprot/hg19//simple_uniprot_Dec012014.bin...
2019-07-17 11:22:37,800 INFO [root:73] Loading /rsrch3/home/lym_myl_rsch/mma/oncotator_v1_ds_April052016/ccle_by_gene/hg19//ccle_results_by_gene.import.bin...
2019-07-17 11:22:37,806 INFO [oncotator.datasources.EnsemblTranscriptDatasource:97] GENCODE v19 is being set up in faster, NOT thread-safe mode (for annotation).
2019-07-17 11:22:37,855 INFO [oncotator.datasources.EnsemblTranscriptDatasource:108] GENCODE v19 is being set up with default tx-mode: CANONICAL.
2019-07-17 11:22:37,855 WARNING [oncotator.datasources.EnsemblTranscriptDatasource:127] Attempting to set transcript mode of CANONICAL for ensembl.  This operation is only supported for GENCODE.  Otherwise, will be the same as EFFECT.
2019-07-17 11:22:37,855 INFO [oncotator.datasources.EnsemblTranscriptDatasource:111] GENCODE v19 is being set up with basic filtering.
Traceback (most recent call last):
  File "/rsrch3/home/lym_myl_rsch/mma/.local/bin/oncotator", line 10, in <module>
    sys.exit(main())
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/Oncotator.py", line 307, in main
    other_opts=other_opts, annotating_type=annotating_type)
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/utils/RunSpecificationFactory.py", line 113, in create_run_spec
    datasource_list = DatasourceFactory.createDatasources(datasource_dir, genomeBuild, isMulticore=is_multicore, numCores=num_cores, tx_mode=tx_mode)
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/DatasourceFactory.py", line 292, in createDatasources
    result.append(DatasourceFactory.createDatasourceGivenTuple(dsTuple))
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/DatasourceFactory.py", line 106, in createDatasourceGivenTuple
    return DatasourceFactory.createDatasource(configTuple[0], configTuple[1])
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/DatasourceFactory.py", line 100, in createDatasource
    return DatasourceFactory.createDatasourceFromConfigParser(configParser, leafDir)
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/DatasourceFactory.py", line 152, in createDatasourceFromConfigParser
    result = Cosmic(src_file=filePrefix + configParser.get('general', 'src_file'), version=configParser.get('general', 'version'), gpp_tabix_file=filePrefix + configParser.get('general', 'gpp_src_file'))
  File "/rsrch3/home/lym_myl_rsch/mma/.local/lib/python2.7/site-packages/oncotator/datasources/Cosmic.py", line 96, in __init__
    header = self.db_genomePos.header.next()
AttributeError: 'list' object has no attribute 'next'
```

**Comment by chunmei1991** [comment]
I have the same problem.Do you have fixed?

**Comment by DaringSky** [comment]
Have anyone fixed it? I also have the same error. 
I installed oncotator v1.9.9.0 on python2.7.11 by anaconda2 and use oncotator_v1_ds_April052016.

![image](https://user-images.githubusercontent.com/39242063/65579809-0d79d280-dfab-11e9-8287-3640f066a59e.png)

**Comment by DaringSky** [comment]
I fixed it! The following is the modified py-file:

`96c96,99
<         header = self.db_genomePos.header.next()
---
>         header = self.db_genomePos.header[0]
>         print '!!!!!!!!!'
>       print(self.db_genomePos.header)
>       print(header)
98c101,102
<
---
>         print self.src_headers
>
100c104,105
<         gppHeader = self.db_geneProteinPos.header.next()
---
>         gppHeader = self.db_geneProteinPos.header[0]
>         print self.db_geneProteinPos.header
102c107
<
---
>       print gppHeader
171c176
<         return tabix_file.fetch(region='%s:%s-%s' % (chromosome, str(start), str(end)))
\ No newline at end of file
---
>         return tabix_file.fetch(region='%s:%s-%s' % (chromosome, str(start), str(end)))`

**Comment by DaringSky** [comment]
I have fixed the 【Cosmic.py】 and now it can run!

**Comment by JohnMCMa** [comment]
Hi @DaringSky ,
Can you provide the fix as a pull request?

**Comment by bdanubius** [comment]
Hi all, has anyone figured this out? Getting the same issues with this python and oncotator version! I didn't see the solution posted as a pull request.

**Comment by lbergelson** [comment]
Oncotator is essentially no longer maintained, development has moved to [Funcotator](https://github.com/broadinstitute/gatk), a GATK tool which provides the same style of annotation but has many bug fixes and improvements.  See this [tutorial for information on how to run funcotator](https://gatk.broadinstitute.org/hc/en-us/articles/360035889931-Funcotator-Information-and-Tutorial).   

It does the same thing, but it's less of pain to install, it's faster, and it has 3 years of bugfixes.

**Comment by bdanubius** [comment]
Unfortunately oncotator seems to be the one used in the broad internal pipelines (RNA Mutect), which require MAF input/output. So a fix for this Oncotator bug is needed...

**Comment by lbergelson** [comment]
@bdanubius. That pipeline is using the original Mutect which has been superseded by the much more powerful Mutect 2.   Is there a more recent pipeline using Mutect2 which produces vcf?

**Comment by lbergelson** [comment]
Oh, I no, it's actually being maintained. It's just the jars which are ancient.  Weird.

**Comment by DaringSky** [comment]
@JohnMCMa 
Sorry, I forgot to set a reminder.

I fixed Cosmic.py, I can provide it for you.

[Cosmic.py.txt](https://github.com/broadinstitute/oncotator/files/4557594/Cosmic.py.txt)

You can compare the raw file, and know where I fixed.
